<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>library_core_tests</RootNamespace>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="files/*.p12">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="files/*.pwd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="files/*.cer">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="files/*.crt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.23" />
    <PackageReference Include="Egelke.Eid.Client" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\library-core\library-core.csproj" />
    <ProjectReference Include="..\pki-module\pki-module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Federation" Version="8.1.2" />
  </ItemGroup>
</Project>