<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <RootNamespace>Egelke.EHealth.Client.Services</RootNamespace>
    <AssemblyName>Egelke.EHealth.Client.Services</AssemblyName>
    <Version>0.1.0</Version>
    <Authors>Egelke BVBA</Authors>
    <Copyright>Copyright © Egelke 2025</Copyright>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\library-core\library-core.csproj" />
    <ProjectReference Include="..\etee-crypto\etee-crypto.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wsdl\cin-encryption\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.2.0" Condition="'$(TargetFramework)' == 'net6.0'" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.3" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.IdentityModel" />
  </ItemGroup>
</Project>
