<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../services/services.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.1" />
    <Content Include="../pki-test/EHealthP12/dummy.p12" Link="fixtures/dummy.p12" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../pki-test/files/fedictTs.ts" Link="fixtures/fedictTs.ts" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
